// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package token

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseGrantedTypeFromString Parse GrantedType from string
func ParseGrantedTypeFromString(str string) (GrantedType, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := GrantedType_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown GrantedType: %s", str)
	}

	return GrantedType(v), nil
}

// Equal type compare
func (t GrantedType) Equal(target GrantedType) bool {
	return t == target
}

// IsIn todo
func (t GrantedType) IsIn(targets ...GrantedType) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t GrantedType) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *GrantedType) UnmarshalJSON(b []byte) error {
	ins, err := ParseGrantedTypeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
